.TH "hexsed" 1 "2016-11-25" "Linux User's Manual"


.SH NAME

.P
\fBhexsed\fR \- a stream editor that uses parameters supplied in hex.

.SH SYNOPSIS

.P
\fBhexsed\fR [\-n] /find/d filename

.P
\fBhexsed\fR [\-n] /find/replace/s filename

.P
Where both find and replace must be strings of hex digits expressed
in ASCII. The edited result is sent to \fIstdout\fR.

.P
\fBhexsed\fR \-[a|e|i|o] char|esc sequence.
Delivers the 2 digit hex ASCII string that represents the input char.

.P
\fBhexsed\fR \-s string
Delivers the 2 didgit hex ASCII string for each byte in string.

.SH DESCRIPTION

.P
\fBhexsed\fR writes the edited content of the input file to \fIstdout\fR. If
the hex sequence to find is not found then the output is a copy of the
input. Optionally it will write a count of the deletions or changes.

.SH OPTIONS

.TP
 \fB\-h\fR
print help information and exit.

.TP
 \fB\-a\fR
char. Outputs the 2 digit hex representation of the char input.

.TP
 \fB\-e\fR
\echar. Outputs the 2 digit hex representation of the escape
sequence input. Single digits only.

.TP
 \fB\-i\fR
decimal digits. Outputs the 2 digit hex representation of the digits input.
Legal range is 0 \- 255, outside range is an error.

.TP
 \fB\-o\fR
octal digits. Outputs the 2 digit hex representation of the digits input.
Legal range is 0 \- 377, outside range is an error.

.TP
 \fB\-s\fR
Null terminated array of bytes. Outputs the 2 digit hex representation
of each byte in the string.

.TP
 \fB\-n\fR
Causes the count of applied expression to be output.

.SH AUTHOR

.P
Robert L Parker rlp1938@gmail.com

.\" man code generated by txt2tags 2.6 (http://txt2tags.org)
.\" cmdline: txt2tags -t man hexsed.t2t
